Vagrant.configure("2") do |config|
  config.vm.box = "relativkreativ/centos-7-minimal"
  
  config.vm.provider "virtualbox" do |v|
    v.name = "tprs_web"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum makecache fast
    sudo yum clean all
    sudo yum update -y
    sudo yum install -y https://centos7.iuscommunity.org/ius-release.rpm
    sudo yum install -y python36u python36u-devel python36u-pip
    sudo yum install -y epel-release
    sudo install ansible
  SHELL
end