# -*- mode: ruby -*-
# vi: set ft=ruby : 

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos8"
  config.ssh.insert_key = false
  config.vm.provider "virtualbox"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
    v.linked_clone = true
    v.customize ['modifyvm', :id, '--audio', 'none']
end

# Define 3 boxes, 1 master 2 node
boxes = [
  { :name => "kube1", :ip => "192.168.7.2" },
  { :name => "kube2", :ip => "192.168.7.3" },
  { :name => "kube3", :ip => "192.168.7.4" }
] 

boxes.each_with_index do |opts, index|
  config.vm.define opts[:name] do |config|
    config.vm.hostname = opts[:name] + ".cluster.test"
    config.vm.network :private_network, ip: opts[:ip]
    end
  end
  
end
